format = "$all$character$status"

[aws]
disabled = true

[env_var]
variable = "AWS_ACCESS_KEY_ID"
symbol = "ğŸ”“"
style = "red bold"
format = "$symbol [with AWS_ACCESS_KEY_ID set]($style)"

[gcloud]
disabled = true

[shlvl]
disabled = false

[status]
disabled = false
map_symbol = true
pipestatus = true
symbol = "âœ–ï¸ "

[character]
success_symbol = "\\(/^ãƒ®^\\)/*:ãƒ»ï¾Ÿâœ§"
error_symbol = "\\(âœ¿âŠ™ï¸¿âŠ™\\)ã¤"
